markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "蜗牛科技"
markdown: rdiscount

author: "dycc"
atom-baseurl: "http://dycc.github.io"
disqus: "gopherwood"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: https://photos.google.com/
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

